# Generated by Django 2.0.9 on 2018-10-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_persons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
