# Generated by Django 2.0.9 on 2018-10-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20181020_0908'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Persons',
        ),
    ]
