# Generated by Django 2.0.9 on 2018-10-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
