# Generated by Django 2.0.9 on 2018-10-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20181020_0951'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
