# Generated by Django 2.0.9 on 2018-10-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20181020_1004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Departments',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employees',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Persons',
        ),
    ]
